#!/bin/bash

# This uses MFA devices to get temporary (eg 12 hour) credentials.  Requires
# a TTY for user input.
#
# GPL 2 or higher

if [ ! -t 0 ]
then
  echo Must be on a tty >&2
  exit 255
fi

if [ -n "$AWS_SESSION_TOKEN" ]
then
  echo "Session token found.  This can not be used to generate a new token.
   unset AWS_SESSION_TOKEN AWS_SECRET_ACCESS_KEY AWS_ACCESS_KEY_ID
and then ensure you have a profile with the normal access key credentials or
set the variables to the normal keys.
" >&2
  exit 255
fi

userarn=$(aws sts get-caller-identity --output text --query Arn)
if [ -z "$userarn" ]
then
  echo "Can not identify who you are.  The output of
  aws sts get-caller-identity --output text --query Arn
did not return an ARN." >&2
  exit 255
fi

username=${userarn##*/}
echo You are: $username >&2

device=$(aws iam list-mfa-devices --user-name "$username" \
    --output text --query 'MFADevices[0].SerialNumber')
if [ -z "$device" ]
then
  echo "Can not find any MFA device for you.  The output of
  aws iam list-mfa-devices --user-name "$username" \
    --output text --query 'MFADevices[0].SerialNumber'
did not return a serial number." >&2
  exit 255
fi

echo Your MFA device is: $device >&2

echo -n "Enter your MFA code now: " >&2
read code

tokens=$(aws sts get-session-token --serial-number "$device" --token-code $code --output text)

set -- $tokens
access=$2
expire=$3
secret=$4
session=$5

if [ -z "$secret" -o -z "$session" -o -z "$access" ]
then
  echo "Unable to get temporary credentials.  Could not find secret/access/session entries

$tokens" >&2
  exit 255
fi

echo export AWS_PROFILE=$AWS_PROFILE
echo export AWS_SESSION_TOKEN=$session
echo export AWS_SECRET_ACCESS_KEY=$secret
echo export AWS_ACCESS_KEY_ID=$access

echo Keys valid until $expire >&2
